<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Web.Poc.Domain.Shared\Web.Poc.Domain.Shared.csproj" />
    <ProjectReference Include="..\Web.Poc.Domain\Web.Poc.Domain.csproj" />
  </ItemGroup>

</Project>
